/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test251;

import com.sun.org.apache.xerces.internal.impl.dv.xs.DecimalDV;
import java.sql.*;
import javax.swing.*;

public class AdminGroups extends javax.swing.JFrame {

    /**
     * Creates new form Groups
     */
    public AdminGroups() {
        initComponents();
        fill_Combo_members();
        //  fill_list();
        fill_list_Users();
        fill_Combo_UsersID();
        setLocationRelativeTo(null);
    }

    final void fill_Combo_members() { // to start open the sql plus , create virtul enviroment
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();

            String query = "SELECT Group_name FROM easyboardGroups";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"
            DefaultComboBoxModel dlm = new DefaultComboBoxModel();

            while (rs.next()) {
                dlm.addElement(rs.getString(1));
            }

            groupNamesCombo.setModel(dlm);
            fill_list_Members();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    final void fill_Combo_UsersID() { // to start open the sql plus , create virtul enviroment
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();

            String query = "SELECT user_id FROM users";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"
            DefaultComboBoxModel dlm = new DefaultComboBoxModel();

            while (rs.next()) {
                dlm.addElement(rs.getString(1));
            }

            usersCombo.setModel(dlm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    final void fill_list_Members() { // to start open the sql plus , create virtul enviroment
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();

            String query = "SELECT User_id FROM group_member where group_name='" + groupNamesCombo.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"
            DefaultListModel dlm = new DefaultListModel();

            while (rs.next()) {
                dlm.addElement(rs.getString(1)); // the position of select statment from table meeting
            }

//            memberList.setModel(dlm);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    final void fill_list_Users() { // to start open the sql plus , create virtul enviroment
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();

            String query = "SELECT user_id FROM users";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"
            DefaultListModel dlm = new DefaultListModel();

            while (rs.next()) {
                dlm.addElement(rs.getString(1)); // the position of select statment from table meeting
            }

       //     usersList.setModel(dlm);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        groupNamesCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usersCombo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        deleteGroup = new javax.swing.JRadioButton();
        deleteMember = new javax.swing.JRadioButton();
        addMember = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        memberList1 = new javax.swing.JList<>();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groupNamesCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        groupNamesCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupNamesComboItemStateChanged(evt);
            }
        });
        jPanel3.add(groupNamesCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 130, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        jLabel1.setText("Group Name:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        jLabel4.setText("Group Member: ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        usersCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel3.add(usersCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 92, -1));

        deleteGroup.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        deleteGroup.setText("Delete Group");
        deleteGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGroupActionPerformed(evt);
            }
        });

        deleteMember.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        deleteMember.setText("Delete employee");
        deleteMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemberActionPerformed(evt);
            }
        });

        addMember.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        addMember.setText("Add employee");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteGroup)
                .addGap(18, 18, 18)
                .addComponent(deleteMember)
                .addGap(18, 18, 18)
                .addComponent(addMember)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteGroup)
                    .addComponent(deleteMember)
                    .addComponent(addMember))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, 530, 70));

        jButton3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 360, -1));

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGE GROUP");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 930, 110));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 420, 20));

        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, 80, 40));

        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 690, 90, 40));

        memberList1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jScrollPane4.setViewportView(memberList1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 180, 170));

        jPanel14.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, 40));

        jPanel15.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, 40));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 26)); // NOI18N
        jLabel7.setText("Employee's LIST:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        jPanel16.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 420, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AdminControl cont = new AdminControl();
        cont.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            //       int taskID = Integer.valueOf(taskidText.getText());
            Statement stm = con.createStatement();

            if (deleteGroup.isSelected()) {
                String query = "DELETE FROM easyboardGroups WHERE group_name ='" + groupNamesCombo.getSelectedItem() + "'";
                stm.execute(query); // to execute query
                JOptionPane.showMessageDialog(null, "The Group is Deleted Succefully");
                fill_Combo_members();
                // fill_list_Members();
                deleteGroup.setSelected(false);
                deleteMember.setSelected(false);
                addMember.setSelected(false);
            }

            if (deleteMember.isSelected()) {
                String query = "DELETE FROM group_member WHERE user_id ='" ;
                stm.execute(query); // to execute query
                JOptionPane.showMessageDialog(null, "The Member is Deleted Succefully");
                //  fill_Combo();
                fill_list_Members();
                deleteGroup.setSelected(false);
                deleteMember.setSelected(false);
                addMember.setSelected(false);
            }

            if (addMember.isSelected()) {
                String query = "INSERT INTO group_member VALUES ('" + usersCombo.getSelectedItem() + "','" + groupNamesCombo.getSelectedItem() + "')";
                stm.execute(query); // to execute query

                JOptionPane.showMessageDialog(null, "The Member is Added Succefully");

                //  fill_Combo_members();
                fill_list_Members();
                deleteGroup.setSelected(false);
                deleteMember.setSelected(false);
                addMember.setSelected(false);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        if (addMember.isSelected()) {
            deleteGroup.setSelected(false);
            deleteMember.setSelected(false);
        }
    }//GEN-LAST:event_addMemberActionPerformed

    private void deleteMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemberActionPerformed
        // TODO add your handling code here:

        if (deleteMember.isSelected()) {
            deleteGroup.setSelected(false);
            addMember.setSelected(false);
        }
    }//GEN-LAST:event_deleteMemberActionPerformed

    private void deleteGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGroupActionPerformed
        // TODO add your handling code here:
        // System.exit(0);

        if (deleteGroup.isSelected()) {
            deleteMember.setSelected(false);
            addMember.setSelected(false);
        }
    }//GEN-LAST:event_deleteGroupActionPerformed

    private void groupNamesComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupNamesComboItemStateChanged
        // TODO add your handling code here:
        fill_list_Members();
    }//GEN-LAST:event_groupNamesComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGroups.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGroups().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addMember;
    private javax.swing.JRadioButton deleteGroup;
    private javax.swing.JRadioButton deleteMember;
    private javax.swing.JComboBox<String> groupNamesCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> memberList1;
    private javax.swing.JComboBox<String> usersCombo;
    // End of variables declaration//GEN-END:variables
}
