/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test251;

import com.sun.org.apache.xerces.internal.impl.dv.xs.DecimalDV;
import java.sql.*;
import javax.swing.*;

public class AdminDecisions extends javax.swing.JFrame {

    /**
     * Creates new form Decisions
     */
    public AdminDecisions() {
        initComponents();
     //   fill_Combo();
        //  fill_listDecisions();
             setLocationRelativeTo(null);
    }

    final void fill_Combo() { // to start open the sql plus , create virtul enviroment
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();

            String query = "SELECT meet_id FROM meeting";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"
            DefaultComboBoxModel dlm = new DefaultComboBoxModel();

            while (rs.next()) {
                dlm.addElement(rs.getString(1));
            }

            meetingCombo.setModel(dlm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    final void fill_listDecisions() { // to start open the sql plus , create virtul enviroment
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();

            String query = "SELECT decisions FROM meet_decisions where meet_id='" + meetingCombo.getSelectedItem() + "'";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"
            DefaultListModel dlm = new DefaultListModel();

            while (rs.next()) {
                dlm.addElement(rs.getString(1));
            }

            ListDecisions.setModel(dlm);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListDecisions = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        meetingCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        meetName1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jButton1.setText("Delete Decision");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 710, -1, -1));

        ListDecisions.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ListDecisions.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListDecisionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListDecisions);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 270, 190));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("Choose meeting ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        meetingCombo.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        meetingCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                meetingComboItemStateChanged(evt);
            }
        });
        meetingCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetingComboActionPerformed(evt);
            }
        });
        jPanel1.add(meetingCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 147, -1));

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE DECISONS ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 970, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 182, 340, 0));

        jLabel8.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 480, 30));

        meetName1.setBackground(new java.awt.Color(255, 51, 102));
        meetName1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        meetName1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(meetName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, 161, 28));

        jTextField2.setText("jTextField1");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 130, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 290, 100));

        jPanel14.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, 40));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("Decisions");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jPanel15.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, 40));

        jButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton4.setText("Main");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 780, 100, 40));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Decision Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        jPanel16.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 480, 30));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Decision Description:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        jPanel17.setBackground(new java.awt.Color(52, 152, 219));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, 40));

        jButton3.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jButton3.setText("Add Decision");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 710, -1, -1));

        jButton5.setFont(new java.awt.Font("Cambria", 1, 20)); // NOI18N
        jButton5.setText("Update Decision");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 710, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 480, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meetingComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_meetingComboItemStateChanged
        // TODO add your handling code here:
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();
            String query = "SELECT name , day , month , year FROM meeting WHERE meet_id='" + meetingCombo.getSelectedItem() + " '";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"

            while (rs.next()) {
                meetName.setText(rs.getString(1));
                dateMeet.setText(rs.getString(2) + "-" + rs.getString(3) + "-" + rs.getString(4));
            }

            fill_listDecisions();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }


    }//GEN-LAST:event_meetingComboItemStateChanged

    private void meetingComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetingComboActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_meetingComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {

            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            //   int meetId = Integer.valueOf(taskidText.getText());
            Statement stm = con.createStatement();
            String query = "INSERT INTO meet_decisions VALUES ('" + meetingCombo.getSelectedItem() + " ','" + decMeet.getText() + "')";
            stm.execute(query); // to execute query

            JOptionPane.showMessageDialog(null, "The Decision is Added Succefully To meeting" + meetingCombo.getSelectedItem());

            fill_listDecisions();
            decMeet.setText(null);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListDecisionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListDecisionsValueChanged
        // TODO add your handling code here:
        try {
            String url = "jdbc:oracle:thin:@localhost:1521:orcl";
            String username = "hr";
            String password = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();
            String query = "SELECT decisions FROM meet_decisions WHERE decisions='" + ListDecisions.getSelectedValue() + "' ";
            ResultSet rs = stm.executeQuery(query); // this is the array that takes the elements of select statments "executing the query"

            while (rs.next()) {
                decMeet.setText(rs.getString(1));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_ListDecisionsValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AdminControl cont = new AdminControl(); // creating an pbject from frame "meetings"
        cont.setVisible(true); // to open frame "Meeting" when the user puch at AdminMeeting button
        this.setVisible(false); // in all forms
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDecisions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDecisions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDecisions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDecisions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDecisions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListDecisions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel meetName1;
    private javax.swing.JComboBox<String> meetingCombo;
    // End of variables declaration//GEN-END:variables
}
